# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCo < Formula
  desc "This tool can be used to manage and switch between multiple kube config files."
  homepage "https://github.com/steffakasid/kubectl-go"
  version "0.24"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.24/kubectl-co_0.24_darwin_amd64.tar.gz"
      sha256 "c9f08a3479955c599c808c313888d943bba5a62e0b69705f90a55199f03726c5"

      def install
        bin.install "kubectl-co"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.24/kubectl-co_0.24_darwin_arm64.tar.gz"
      sha256 "2e109cfd7028d8a9166eb96fae1ed57fafa2a830d61b42dd4697ab81925e2732"

      def install
        bin.install "kubectl-co"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.24/kubectl-co_0.24_linux_amd64.tar.gz"
      sha256 "8f91dfa83b3ccd30f4e8f9d98e9107a01f8505a962e766832467697cfeec9177"
      def install
        bin.install "kubectl-co"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.24/kubectl-co_0.24_linux_arm64.tar.gz"
      sha256 "22d634fffc8619a43ca23975d6f8ae72e9d4bfd53937d1b4a914ce85dec6c7e4"
      def install
        bin.install "kubectl-co"
      end
    end
  end
end
