# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCo < Formula
  desc "This tool can be used to manage and switch between multiple kube config files."
  homepage "https://github.com/steffakasid/kubectl-go"
  version "0.17"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.17/kubectl-co_0.17_darwin_amd64.tar.gz"
      sha256 "e56d552d04d623cb680a9068d55241bc4e02e142f5256d69c0dddad76733cf36"

      def install
        bin.install "kubectl-co"
      end
    end
    on_arm do
      url "https://github.com/steffakasid/kubectl-co/releases/download/v0.17/kubectl-co_0.17_darwin_arm64.tar.gz"
      sha256 "09e336d83eff139dd0b049c1a22734980944e57dbfe62fd39975a90ad2659878"

      def install
        bin.install "kubectl-co"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v0.17/kubectl-co_0.17_linux_amd64.tar.gz"
        sha256 "8dd8c114d98dd3028f2a3e076f055b482481cb25944f0c343f797115f62a3604"

        def install
          bin.install "kubectl-co"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/steffakasid/kubectl-co/releases/download/v0.17/kubectl-co_0.17_linux_arm64.tar.gz"
        sha256 "79cf596b06c448e42395025484dd88f28e184f4f0fe6a5c4f37ef4a042a939af"

        def install
          bin.install "kubectl-co"
        end
      end
    end
  end
end
